### ISSUE TITLE
bugs in `MeasureSearch`

### ISSUE THREAD

**Issue by JacksonBurns** [VlachosGroup/molSim#166]
- unreachable code in `_extract_configs` [here](https://github.com/VlachosGroup/molSim/blob/0793231db4a54062c82ff583c5a73ad2f1b79750/molSim/tasks/measure_search.py#L49). `self.log_fpath` will always be `None` because the constructor sets it as such right before this method is called.
 - `self.log_fpath` is never used for logging
 - calling `MeasureSearch` with both `only_metric=True` and `fingerprint_type='morgan_fingerprint` causes an Index out of range error. Reproduce with the snippet below (smiles_seq_to_textfile from the testing files):
 ```
properties = np.random.normal(size=len(self.test_smiles))
text_fpath = self.smiles_seq_to_textfile(property_seq=properties)
msearch = MeasureSearch()
msearch.get_best_measure(
                molecule_set_configs={
                    'molecule_database_src': text_fpath,
                    'molecule_database_src_type': 'text',
                },
                subsample_subset_size=1.0,
                only_metric=True,
                similarity_measure='tanimoto',
            )
```
 - constructor has no documentation

**Comment by himaghna** [comment]
@JacksonBurns : Solved 1 and 2. Could not reproduce with code:
`
from molSim.chemical_datastructures import Molecule
from molSim.tasks.measure_search import MeasureSearch
import numpy as np

test_smiles = [
        "CCCCCCC",
        "CCCC",
        "CCC",
        "CO",
        "CN",
        "C1=CC=CC=C1",
        "CC1=CC=CC=C1",
        "C(=O)(N)N",
    ]


def smiles_seq_to_textfile(property_seq=None):
    text_fpath = "temp_smiles_seq.txt"
    print(f"Creating text file {text_fpath}")
    with open(text_fpath, "w") as fp:
        for id, smiles in enumerate(test_smiles):
            write_txt = smiles
            if property_seq is not None:
                write_txt += " " + str(property_seq[id])
            if id < len(test_smiles) - 1:
                write_txt += "\n"

            fp.write(write_txt)
    return text_fpath


properties = np.random.normal(size=len(test_smiles))
text_fpath = smiles_seq_to_textfile(property_seq=properties)
msearch = MeasureSearch()
msearch.get_best_measure(molecule_database_src=text_fpath,
                         molecule_database_src_type='text',
                         subsample_subset_size=1.0,
                         only_metric=True,
                         similarity_measure=None,
                         fingerprint_type='morgan_fingerprint')

`
