### ISSUE TITLE
Similarity PDF and Heatmap both always generated

### ISSUE THREAD

**Issue by ericchen-udel** [VlachosGroup/molSim#171]
When only Similarity PDF or only Similarity Heatmap are checked, both are always generated. 

Attached is the input file use
[smiles.txt](https://github.com/VlachosGroup/molSim/files/7947695/smiles.txt)

GitHub can't pload ui config file, but here it is:

fingerprint_type: morgan_fingerprint
is_verbose: true
molecule_database: smiles.txt
molecule_database_source_type: text
n_workers: 1
similarity_measure: peirce_1
tasks:
  visualize_dataset:
    pairwise_heatmap_settings:
      annotate: false
      cmap: viridis

**Comment by JacksonBurns** [comment]
This is actually a holdover from an earlier iteration of molSim. Previously, one could specify whether to generate the PDF and/or the Heatmap, but now they are both _always_ generated. I am going to update the UI to reflect this, rather than revert the code to the previous version.
